### ISSUE TITLE
After droping the WS db the villages already synchronized are not deleted

### ISSUE THREAD

**Issue by arturonaredo** [jonatantierno/huggingNepal#2]
Just for tracking the bugs....

We should study the behaviour desired.

Maybe if the WS database is empty erase all the villages "already synchronized" and not in draft state when receiving a empty json array? 

Cheers,
Arturo

**Comment by jonatantierno** [comment]
I think this would work as a temporal solution, although we would do good to think a bit deeper about the protocol, and decide if we want to implement paging, or send the date of the last backup so not all data is sent, but all the delta... What do you think?

**Comment by arturonaredo** [comment]
Closed issue given this app new feature that stops earthquakes.
